/* -*-  Mode: C++; c-file-style: "gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2018
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Samuel Salvatella <ssalvatellaperez@gmail.com>
 *
 *
 * This example demonstrates the use of ElectricMobilityHelper class to work with mobility.
 *
 * Detailed example description.
 *
 *  - intended usage: this should be used in order to load ns2 movement trace files and a xml file that specifies the attributes of each electric vehicle
 *                    to simulate the consumption of each vehicle associated with a node of the traces
 *  - behavior:
 *      - ElectricMobilityHelper object is created, associated to the specified trace file. 
 *      - A log file is created, using the log file name argument.
 *      - A node container is created with the number of nodes specified in the command line.  For the default ns-2 trace, specify the value 2 for this argument.
 *      - the program calls the Install() method of ElectricMobilityHelper to set mobility to nodes. At this moment, the file is read line by line, and the movement is scheduled in the simulator.
 *      - A callback is configured, so each time a node changes its course a log message is printed.
 *  - expected output: example prints out messages generated by each read line from the ns2 movement trace file.
 *                     For each line, it shows if the line is correct, or of it has errors and in this case it will
 *                     be ignored.
 *
 * Usage of electric-mobility:
 *
 *  ./waf --run "electric-mobility \
 *        --traceFile=src/mobility/examples/default.ns_movements --vehicleAttributes=src/mobility/examples/vehicleAttributes.xml
 *        --nodeNum=2  --duration=100.0 --logFile=electric-mobility.log"
 *
 *  NOTE: ns2-traces-file could be an absolute or relative path. You could use the file default.ns_movements
 *        included in the same directory as the example file.
 *  NOTE 2: Number of nodes present in the trace file must match with the command line argument.
 *          Note that you must know it before to be able to load it.
 *  NOTE 3: Duration must be a positive number and should match the trace file. Note that you must know it before to be able to load it.
 */

#include <iostream>
#include <fstream>
#include <sstream>

#include "ns3/core-module.h"
#include "ns3/mobility-module.h"
#include "ns3/mobility-module.h"
#include "ns3/ns2-mobility-helper.h"
#include "electric-mobility-helper.h"

using namespace ns3;

// Example to use ns2 traces file and xml file to simulate consumption of electric vehicles
int main (int argc, char *argv[])
{
  std::string traceFile;
  std::string vehicleAttributesFile;
  std::string logFile;

  int    nodeNum;
  double duration;

  // Parse command line attribute
  CommandLine cmd;
  cmd.AddValue ("traceFile", "Ns2 movement trace file", traceFile);
  cmd.AddValue ("vehicleAttributes", "Vehicle Attributes", vehicleAttributesFile);
  cmd.AddValue ("logFile", "Log file", logFile);
  cmd.AddValue ("nodeNum", "Number of nodes", nodeNum);
  cmd.AddValue ("duration", "Duration of Simulation", duration);
  cmd.Parse (argc,argv);

  // Check command line arguments
  if (traceFile.empty () || vehicleAttributesFile.empty () || nodeNum <= 0 || duration <= 0 || logFile.empty ())
    {
      std::cout << "Usage of " << argv[0] << " :\n\n"
      "./waf --run \"electric-mobility"
      " --traceFile=src/mobility/examples/default.ns_movements"
      " --vehicleAttributes=src/mobility/examples/vehicleAttributes.xml"
      " --nodeNum=2 --duration=100.0 --logFile=electric-mobility.log\" \n\n"
      "NOTE: ns2-traces-file could be an absolute or relative path. You could use the file default.ns_movements\n"
      "      included in the same directory of this example file.\n\n"
      "NOTE 2: Number of nodes present in the trace file must match with the command line argument and must\n"
      "        be a positive number. Note that you must know it before to be able to load it.\n\n"
      "NOTE 3: Duration must be a positive number. Note that you must know it before to be able to load it.\n\n";

      return 0;
    }



  // Create Ns2MobilityHelper with the specified trace log file as parameter
  Ns2MobilityHelper ns2 = Ns2MobilityHelper (traceFile);

  // Create ElectricMobilityHelper with the xml of vehicle attributes
  ElectricMobilityHelper electricMobility = ElectricMobilityHelper (vehicleAttributesFile, ns2, logFile);

  // Create all nodes.
  NodeContainer stas;
  stas.Create (nodeNum);

  ns2.Install (); // configure movements for each node, while reading trace file
  electricMobility.Install (); // configure the vehicle attributes for each node

  Simulator::Stop (Seconds (duration));
  Simulator::Run ();
  Simulator::Destroy ();

  //os.close (); // close log file
  return 0;
}